# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1yLwqojFks-SMMomlSTk2sGArXs8AnT
"""

! pip install streamlit -q

!pip install PyPortfolioOpt
!pip install skfolio

!pip install streamlit pandas numpy plotly scipy ipywidgets scikit-learn openpyxl seaborn matplotlib pyvis cvxpy pyngrok fpdf

!pip install streamlit-aggrid

!pip install xlsxwriter

!pip install fpdf

!pip install plotly numpy kaleido pandas streamlit scipy yfinance

!pip install streamlit pandas numpy scipy pyngrok statsmodels matplotlib seaborn

!pip install pyngrok

from pyngrok import ngrok
# (facultatif) Ajoute ton token si tu veux des sessions longues
ngrok.set_auth_token("30N3JbmXTlamflqYe5uN4SYslbm_rFvrGszAXDHTvLZTvyaG")

from pyngrok import ngrok
import time
# D'abord tuer tous les tunnels existants
ngrok.kill()

# Attendre un peu pour que la fermeture prenne effet
time.sleep(2)

# Créer un nouveau tunnel avec un nom spécifique
public_url = ngrok.connect(8501, bind_tls=True)
print(f"🚀 URL publique : {public_url}")

# Lancer Streamlit
!nohup streamlit run app.py --server.port 8501 > log.txt 2>&1 &

